<?php

return [
    'auditor_required' => [
        'title' => 'Auditor Required',
        'message' => 'There is only one auditor (:auditor_name) in competition ":competition_title". If you don\'t assign another auditor within 1 day, your competition will be deleted.',
    ],
    'admin_deletion_failed' => [
        'title' => 'Admin Deletion Failed',
        'message' => 'Cannot delete admin: they are the only auditor in some competitions.',
    ],
    'job_completed' => [
        'title' => 'Job Completed',
        'message' => 'The job has been completed successfully.',
    ],
    'job_failed' => [
        'title' => 'Job Failed',
        'message' => 'The job has failed. Please check the details.',
    ],
    // Competition notifications
    'competition' => [
        'created' => [
            'title' => 'New Competition Created',
            'message' => 'A new competition ":competition_title" has been created and you are eligible to participate.',
        ],
        'updated' => [
            'title' => 'Competition Updated',
            'message' => 'The competition ":competition_title" has been updated with new information.',
        ],
        'activated' => [
            'title' => 'Competition Started',
            'message' => 'The competition ":competition_title" has started! Get ready to participate.',
        ],
        'user_added' => [
            'title' => 'Added to Competition',
            'message' => 'You have been added to the competition ":competition_title". Welcome!',
        ],
        'level_created' => [
            'title' => 'New Level Added',
            'message' => 'A new level ":level_name" has been added to competition ":competition_title".',
        ],
        'level_updated' => [
            'title' => 'Level Updated',
            'message' => 'The level ":level_name" in competition ":competition_title" has been updated.',
        ],
        'level_activated' => [
            'title' => 'Level Started',
            'message' => 'Level ":level_name" in competition ":competition_title" has started! Duration: :duration',
        ],
        'level_finished' => [
            'title' => 'Level Completed',
            'message' => 'Level ":level_name" in competition ":competition_title" has been completed.',
        ],
        'auditor_requested' => [
            'title' => 'Auditor Request',
            'message' => 'You have been requested to be an auditor for ":competition_title"',
        ],
        'level_manager_requested' => [
            'title' => 'Level Manager Request',
            'message' => 'You have been requested to be a level manager for ":level_name" in ":competition_title"',
        ],
        'audit_level_requested' => [
            'title' => 'Audit Level Request',
            'message' => 'The Level :level_name in :competition_title finished, you have to audit users responses as soon as possible',
        ],

        'confirm_ai_auditing_level_requested' => [
            'title' => 'Confirm AI Auditing Level Request',
            'message' => 'The Level :level_name in :competition_title finished, you have to confirm the scores generated by AI to uses, after :minutes minutes you will be considered as confirmed',
        ],
    ],
    // Link text translations
    'link_text' => [
        'detail' => 'Show Detail',
        'see_more' => 'See More',
        'view' => 'View',
    ],
    'notifications' => 'Notifications',
    'type' => 'Type',
    'title' => 'Notification',
    'data' => 'Detail',
    'created_at' => 'Created At',
    'detail_modal' => [
        'title' => 'Notification Details',
    ],
    'view_all_notifications' => 'View All Notifications',
    // Approval notifications
    'approval' => [
        'level_manager_requested' => [
            'title' => 'Level Manager Request',
            'message' => 'You have been requested to be a level manager for ":level_name" in ":competition_title"',
        ],
        'auditor_requested' => [
            'title' => 'Auditor Request',
            'message' => 'You have been requested to be an auditor for ":competition_title"',
        ],
        'approved' => [
            'title' => 'Request Approved',
            'message' => ':admin_name approved your :approval_type request for ":competition_title"',
        ],
        'rejected' => [
            'title' => 'Request Rejected',
            'message' => ':admin_name rejected your :approval_type request for ":competition_title"',
        ],
    ],
    // Payment notifications
    'payment' => [
        // Admin Notifications (minimal data)
        'transaction_created' => [
            'title' => 'New Payment Submitted',
            'message' => ':payer_name (:payer_type) submitted a payment of :amount. Transaction: :transaction_uuid'
        ],
        'review_requested' => [
            'title' => 'Payment Review Requested',
            'message' => ':payer_name (:payer_type) requested a review for transaction :transaction_uuid'
        ],
        
        // User Notifications (minimal data)
        'transaction_approved' => [
            'title' => 'Payment Approved',
            'message' => 'Your payment of :amount has been approved! :coins_credited coins credited.'
        ],
        'transaction_rejected' => [
            'title' => 'Payment Rejected',
            'message' => 'Your payment of :amount has been rejected. Please check the details.'
        ],
        'transaction_cancelled' => [
            'title' => 'Payment Cancelled',
            'message' => 'Your payment of :amount has been cancelled.'
        ],
        'review_approved' => [
            'title' => 'Review Approved',
            'message' => 'Your review request has been approved. :coins_credited coins credited.'
        ],
        'review_rejected' => [
            'title' => 'Review Rejected',
            'message' => 'Your review request has been rejected. Please contact support.'
        ]
    ],
]; 