<?php

namespace App\Repository\GuestUsers;

use App\Helpers\PaginationHelper;
use App\Interface\GuestUsers\UserGuestRepositoryInterface;
use App\Models\GuestUsers\Choice;
use App\Models\GuestUsers\GlobalQuestion;
use App\Models\GuestUsers\GlobalResponse;

// This repository is responsible ONLY for data access (CRUD) operations.
// All business logic, validation, and coordination should be handled in the Service layer.
class UserGuestRepository implements UserGuestRepositoryInterface
{
    // Find a choice by ID
    public function findChoice($choiceId)
    {
        return Choice::findOrFail($choiceId);
    }

    // Create a new GlobalResponse
    public function createResponse(array $data)
    {
        return GlobalResponse::create($data);
    }

    // Update a GlobalResponse by ID
    public function updateResponse($responseId, array $data)
    {
        $response = GlobalResponse::findOrFail($responseId);
        $response->update($data);
        return $response;
    }

    // Get the latest response for a user and question where choice_id is null
    public function getLatestPendingResponse($questionId, $userId)
    {
        return GlobalResponse::where([
            'question_id' => $questionId,
            'user_id' => $userId,
            'choice_id' => null,
        ])->orderBy('created_at', 'desc')->first();
    }

    // Get paginated questions with user responses
    public function getUserRespondedQuestionsPaginated($userId)
    {
        return GlobalQuestion::whereHas('responses', function ($query) use ($userId) {
                $query->where('user_id', $userId);
            })
            ->with(['responses' => function ($query) use ($userId) {
                $query->where('user_id', $userId)->with('choice');
            }])
            ->paginate(PaginationHelper::perPage());
    }

    // Get a question by ID
    public function findQuestion($questionId)
    {
        return GlobalQuestion::findOrFail($questionId);
    }

    // Fetch one random approved question with choices, for which the user has:
    // - never answered, OR
    // - exactly one response with score=0
    // After two responses (even if both are wrong), the question is no longer shown
    public function getRandomEligibleQuestionForUser($userId)
    {
        // Try to get an approved non-AI question first (most common case)
        $approvedQuestion = GlobalQuestion::with(['choices'])
            ->where('ai', false)
            ->whereNotNull('approved')
            ->where(function ($query) use ($userId) {
                // No responses by this user
                $query->whereDoesntHave('responses', function ($q) use ($userId) {
                    $q->where('user_id', $userId);
                })
                // OR exactly one response with score = 0
                ->orWhereHas('responses', function ($q) use ($userId) {
                    $q->where('user_id', $userId)
                        ->where('score', 0);
                }, '=', 1)
                ->whereDoesntHave('responses', function ($q) use ($userId) {
                    $q->where('user_id', $userId)
                        ->where('score', '>', 0);
                });
            })
            ->inRandomOrder()
            ->first();

        if ($approvedQuestion) {
            return $approvedQuestion;
        }

        // Fallback to user's own questions if no approved questions available
        return $this->getRandomAIQuestionForUser($userId);
    }

    // Fetch one random AI question generated by the specific user
    public function getRandomAIQuestionForUser($userId, $questionId = null)
    {
        $query = GlobalQuestion::with(['choices'])
            ->where('ai', true)
            ->where('user_id', $userId)
            ->where(function ($query) use ($userId) {
                // No responses by this user
                $query->whereDoesntHave('responses', function ($q) use ($userId) {
                    $q->where('user_id', $userId);
                })
                // OR exactly one response with score = 0
                ->orWhereHas('responses', function ($q) use ($userId) {
                    $q->where('user_id', $userId)
                        ->where('score', 0);
                }, '=', 1)
                ->whereDoesntHave('responses', function ($q) use ($userId) {
                    $q->where('user_id', $userId)
                        ->where('score', '>', 0);
                });
            });

        if ($questionId) {
            $query->where('id', $questionId);
        }else{
            $query->inRandomOrder();
        }

        return $query->first();
    }

    // Fetch one random premium AI question (after 48 hours exclusivity)
    public function getRandomPremiumQuestionForUser($userId)
    {
        return GlobalQuestion::with(['choices'])
            ->whereNotNull('approved')
            ->where('ai', true)
            ->where('created_at', '<=', now()->subHours(48)) // After 48 hours
            ->where(function ($query) use ($userId) {
                // No responses by this user
                $query->whereDoesntHave('responses', function ($q) use ($userId) {
                    $q->where('user_id', $userId);
                })
                // OR exactly one response with score = 0
                ->orWhereHas('responses', function ($q) use ($userId) {
                    $q->where('user_id', $userId)
                        ->where('score', 0);
                }, '=', 1)
                ->whereDoesntHave('responses', function ($q) use ($userId) {
                    $q->where('user_id', $userId)
                        ->where('score', '>', 0);
                });
            })
            ->inRandomOrder()
            ->first();
    }
}
